### ISSUE TITLE
HTML 5 validation is not working because form is not semantically correct

### ISSUE THREAD

**Issue by kieranklaassen** [marcd123/StickyBooking#15]
I like you implemented html5 validation:

![mean_stack_programming_lessons](https://user-images.githubusercontent.com/209089/32180484-1688a6fe-bd60-11e7-96fc-d00f0baa2a06.png)

The only thing is that they do not work because of 2 things:

1. You do not have a form element around the inputs
2. You do not submit the form

![mean_stack_programming_lessons](https://user-images.githubusercontent.com/209089/32180571-562607de-bd60-11e7-9e61-d99076476153.png)

How you would semantically use a form with Angular is by using ng-submit: https://docs.angularjs.org/api/ng/directive/ngSubmit

**Comment by marcd123** [comment]
Ended up really restructuring the HTML in the customer info pane so that I could actually fit all of the different checkout forms and error alert box into one form. This resulted in some good design improvements and cleaner code as a side effect.

Anyway, now the form will not submit if any required fields are not filled including dynamic questions that are required. When the form does submit it will check your PSP and continue down the correct path.
